# Generated by Django 5.0.4 on 2026-05-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom', '0003_vulnerability'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbomupload',
            name='hashcode',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
