# Generated by Django 5.0.4 on 2026-05-05 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_product_business_unit_product_created_by_and_more'),
        ('sbom', '0004_sbomupload_hashcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbomupload',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='organizations.product'),
        ),
    ]
