# Generated by Django 5.0.4 on 2026-05-10 17:01

import apps.sbom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom', '0005_sbomupload_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbomupload',
            name='sbom_file',
            field=models.FileField(upload_to=apps.sbom.models.upload_to_uuid),
        ),
    ]
