# Generated by Django 5.0.4 on 2026-05-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom', '0006_alter_sbomupload_sbom_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbomupload',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
