# Generated by Django 5.0.4 on 2026-05-25 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom', '0008_vulnerability_epss_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VexStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('doc_version', models.PositiveIntegerField(default=1)),
                ('doc_time_first_issued', models.DateTimeField(auto_now_add=True)),
                ('doc_time_last_updated', models.DateTimeField(auto_now=True)),
                ('tooling', models.CharField(default='Matrix SBOM Monitor', editable=False, max_length=100)),
                ('statement_version', models.PositiveIntegerField(default=1)),
                ('statement_time_first_issued', models.DateTimeField(auto_now_add=True)),
                ('statement_time_last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('under_investigation', 'Under Investigation'), ('affected', 'Affected'), ('not_affected', 'Not Affected'), ('fixed', 'Fixed')], default='under_investigation', max_length=50)),
                ('justification', models.CharField(blank=True, choices=[('component_not_present', 'Component Not Present'), ('vulnerable_code_not_present', 'Vulnerable Code Not Present'), ('vulnerable_code_not_in_execute_path', 'Vulnerable Code Not in Execute Path'), ('vulnerable_code_cannot_be_controlled_by_adversary', 'Vulnerable Code Cannot Be Controlled by Adversary'), ('inline_mitigations_already_exist', 'Inline Mitigations Already Exist')], max_length=100, null=True)),
                ('impact_statement', models.TextField(blank=True, null=True)),
                ('action_statement', models.TextField(blank=True, null=True)),
                ('status_notes', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vex_statements', to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vex_statements', to='sbom.vulnerability')),
            ],
            options={
                'verbose_name': 'VEX Statement',
                'verbose_name_plural': 'VEX Statements',
                'ordering': ['-statement_time_last_updated'],
            },
        ),
    ]
