# Generated by Django 5.0.4 on 2026-05-30 18:25

import apps.sbom.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom', '0009_vexstatement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='cpe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sbomupload',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sbomupload',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sbomupload',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sbom_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sbomupload',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload SBOM'), ('rauc', 'RAUC Bundle'), ('csv', 'CSV Manual')], default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='sbomupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sbom_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sbomupload',
            name='sbom_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.sbom.models.upload_to_uuid),
        ),
        migrations.AlterField(
            model_name='sbomupload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falha'), ('VALIDATION', 'Em Validação'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20),
        ),
    ]
