# Generated by Django 5.0.4 on 2026-05-10 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sbom', '0006_alter_sbomupload_sbom_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HbomUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sbom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hbom', to='sbom.sbomupload')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CPU', 'Processador / SoC'), ('MCU', 'Microcontrolador'), ('BLUETOOTH', 'Bluetooth'), ('WIFI', 'Wi-Fi'), ('CELLULAR', 'Celular / GSM / LTE'), ('FLASH', 'Memória Flash'), ('RAM', 'Memória RAM'), ('CRYPTO', 'Criptografia / TPM / SE'), ('PMIC', 'Gerenciamento de energia'), ('SENSOR', 'Sensor'), ('GPS', 'GPS / GNSS'), ('DISPLAY', 'Display'), ('CAMERA', 'Câmera'), ('AUDIO', 'Áudio'), ('OTHER', 'Outro')], max_length=50)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('interfaces', models.JSONField(blank=True, default=list)),
                ('secure_boot', models.BooleanField(default=False)),
                ('firmware_signed', models.BooleanField(default=False)),
                ('encrypted_storage', models.BooleanField(default=False)),
                ('debug_ports_disabled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hbom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hbom.hbomupload')),
            ],
        ),
    ]
