# Generated by Django 5.0.4 on 2026-05-10 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentThreat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threat_id', models.CharField(max_length=20)),
                ('threat_name', models.CharField(max_length=255)),
                ('triggered_by_pids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='hbom.hardwarecomponent')),
            ],
            options={
                'unique_together': {('component', 'threat_id')},
            },
        ),
        migrations.CreateModel(
            name='ThreatMitigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mitigation_id', models.CharField(max_length=20)),
                ('mitigation_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RESOLVED', 'Corrigida'), ('ACCEPTED', 'Risco Aceito')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('component_threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='hbom.componentthreat')),
            ],
            options={
                'unique_together': {('component_threat', 'mitigation_id')},
            },
        ),
    ]
