"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import environ
import os
from pathlib import Path
from apps import * 

env = environ.Env(DEBUG=(bool, False))
BASE_DIR = Path(__file__).resolve().parent.parent

# Read the .env file located at the project root (matrix/.env)
environ.Env.read_env(os.path.join(BASE_DIR, '..', '.env'))

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = ['*'] # Para desenvolvimento local

# Increase upload limit to 100 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600 
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600

SESSION_COOKIE_SAMESITE = 'Lax'          # Protects against cross-site CSRF
SESSION_EXPIRE_AT_BROWSER_CLOSE = True   # Session ends when the browser closes
SESSION_COOKIE_AGE = 3600                # Maximum session lifetime: 1 hour



# File storage path inside the container
MEDIA_ROOT = '/data/uploads'
# URL for accessing uploaded files via browser
MEDIA_URL = '/media/'

CSRF_TRUSTED_ORIGINS = [
    "https://localhost:8000",
    "http://localhost:8000",
    "https://localhost",
    "http://localhost",
    "https://cuddly-pancake-j99jw657qj35vwx-8000.app.github.dev",
    "http://cuddly-pancake-j99jw657qj35vwx-8000.app.github.dev",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'mozilla_django_oidc',
    'usuarios',
    'apps.vulnerabilities',
    'apps.organizations',
    'apps.rootfs',
    'apps.sbom',
    'apps.accounts.apps.AccountsConfig',
    'apps.hunting',
    'apps.hbom',
    'apps.archive',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.accounts.middleware.ForcePasswordChangeMiddleware',
    'axes.middleware.AxesMiddleware',  # must be last
]

ROOT_URLCONF = 'config.urls'

BASE_DIR = Path(__file__).resolve().parent.parent # Isso aponta para /matrix/app

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Adiciona a pasta raiz dos apps para encontrar o login.html
            os.path.join(BASE_DIR, 'apps/accounts'), 
            # Adiciona a pasta global de templates para o dashboard
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

LOGOUT_REDIRECT_URL = '/accounts/login'
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}

# Caso queira mapear explicitamente para garantir:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': 'db',      # Service name in docker-compose
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'pt-br'

LANGUAGES = [
    ('pt-br', _('Português')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Redirect the user to the home page (or dashboard) after login
LOGIN_REDIRECT_URL = '/'


# Additional static files paths
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# DEVELOPMENT ONLY — remove in production
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]


# ─────────────────────────────────────────────────────────────
# Adicionar no final de config/settings.py
# ─────────────────────────────────────────────────────────────

from celery.schedules import crontab

# Broker e backend (Redis)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_TIMEZONE = 'America/Sao_Paulo'

CELERY_BEAT_SCHEDULE = {

    # 1. Update Grype database daily at 02:00
    'update-grype-db-daily': {
        'task': 'tasks.scheduled_tasks.update_grype_db',
        'schedule': crontab(hour=2, minute=0),
    },

    # 2. Re-scan all active SBOMs daily at 03:00 (after the Grype update)
    'daily-rescan-all-sboms': {
        'task': 'tasks.scheduled_tasks.daily_rescan_all',
        'schedule': crontab(hour=3, minute=0),
    },

    # 3. Check PG↔Neo4j integrity daily at 05:00
    'daily-integrity-check': {
        'task': 'tasks.scheduled_tasks.daily_integrity_check',
        'schedule': crontab(hour=5, minute=0),
    },
}

# ─────────────────────────────────────────────────────────────
# Authentication backends
# ─────────────────────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',              # bloqueio por tentativas
    'apps.accounts.oidc_backend.MatrixOIDCBackend',     # Keycloak OIDC
    'django.contrib.auth.backends.ModelBackend',         # login local
]

# ─────────────────────────────────────────────────────────────
# Keycloak / OIDC (mozilla-django-oidc)
# ─────────────────────────────────────────────────────────────
OIDC_RP_CLIENT_ID     = os.getenv('OIDC_RP_CLIENT_ID', '')
OIDC_RP_CLIENT_SECRET = os.getenv('OIDC_RP_CLIENT_SECRET', '')

# Algoritmo RS256 — padrão Keycloak moderno
OIDC_RP_SIGN_ALGO = 'RS256'

# Endpoints do Keycloak corporativo — configurar via variável de ambiente OIDC_OP_BASE_URL
# Padrão: https://SEU_KEYCLOAK/auth/realms/SEU_REALM/protocol/openid-connect/
_KC_BASE = os.getenv('OIDC_OP_BASE_URL', '')
OIDC_OP_AUTHORIZATION_ENDPOINT = f'{_KC_BASE}/auth'
OIDC_OP_TOKEN_ENDPOINT          = f'{_KC_BASE}/token'
OIDC_OP_USER_ENDPOINT           = f'{_KC_BASE}/userinfo'
OIDC_OP_JWKS_ENDPOINT           = f'{_KC_BASE}/certs'
OIDC_OP_LOGOUT_ENDPOINT         = f'{_KC_BASE}/logout'

# Não cria usuário automaticamente — deve existir previamente no Matrix
OIDC_CREATE_USER = False

# Redireciona após login/logout
LOGIN_REDIRECT_URL  = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Renova o token a cada 15 minutos
OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = 900

# ─────────────────────────────────────────────────────────────
# django-axes — bloqueio por tentativas malsucedidas
# ─────────────────────────────────────────────────────────────
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']
AXES_LOCKOUT_TEMPLATE = None
AXES_VERBOSE = False