# Generated by Django 5.0.4 on 2026-04-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rootfs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Crítico'), ('HIGH', 'Alto'), ('MEDIUM', 'Médio'), ('LOW', 'Baixo'), ('UNKNOWN', 'Desconhecido')], max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('package_name', models.CharField(max_length=255)),
                ('package_version', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('fix_status', models.CharField(blank=True, max_length=100, null=True)),
                ('rootfs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='rootfs.rootfs')),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
            },
        ),
    ]
