# Generated by Django 5.0.4 on 2026-05-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do parâmetro. Ex: weight_cvss, multiplier_known_exploited', max_length=100, unique=True)),
                ('value', models.FloatField(help_text='Valor numérico do parâmetro')),
                ('description', models.TextField(blank=True, help_text='Descrição do que este parâmetro controla')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Risco',
                'verbose_name_plural': 'Configurações de Risco',
            },
        ),
    ]
