# Generated by Django 5.0.4 on 2026-04-28 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootFS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('internal_name', models.UUIDField(default=uuid.uuid4)),
                ('file_path', models.FilePathField(path='/rootfs')),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pendente'), ('GENERATING_SBOM', 'Gerando SBOM'), ('SCANNING_VULNS', 'Escaneando Vulnerabilidades'), ('INGESTING', 'Ingerindo Dados'), ('COMPLETED', 'Concluído'), ('ERROR', 'Erro')], default='PENDING', max_length=20)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rootfs_files', to='organizations.product')),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('level', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rootfs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rootfs.rootfs')),
            ],
        ),
    ]
