# Generated by Django 5.0.4 on 2026-05-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootfs',
            name='bundle_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
