# Generated by Django 5.0.4 on 2026-05-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootfs', '0002_rootfs_bundle_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootfs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
